# Introducción a NumPy

[Numpy](https://numpy.org) es una librería fundamental para la computación científica con Python.
* Proporciona arrays N-dimensionales
* Implementa funciones matemáticas sofisticadas
* Proporciona mecanismos para facilitar la realización de tareas relacionadas con álgebra lineal o números aleatorios

## Imports

## Arrays

Un **array** es una estructura de datos que consiste en una colección de elementos (valores o variables), cada uno identificado por al menos un índice o clave. Un array se almacena de modo que la posición de cada elemento se pueda calcular a partir de su tupla de índice mediante una fórmula matemática. El tipo más simple de array es un array lineal, también llamado array unidimensional.

En numpy:
* Cada dimensión se denomina **axis**
* El número de dimensiones se denomina **rank**
* La lista de dimensiones con su correspondiente longitud se denomina **shape**
* El número total de elementos (multiplicación de la longitud de las dimensiones) se denomina **size**

In [1]:
# Array cuyos valores son todo 0


_**a**_ es un array:
* Con dos **axis**, el primero de longitud 2 y el segundo de longitud 4
* Con un **rank** igual a 2
* Con un **shape** igual (2, 4)
* Con un **size** igual a 8

## Creación de Arrays

In [2]:
# Array cuyos valores son todo 0


In [3]:
# Array cuyos valores son todo 1


In [4]:
#Array cuyos valores son todos   el valor indicado como segundo  parámetro


In [5]:
#El resultado de np.empty no es predecible
# inicializa los valores con lo que tenga en memoria

In [6]:
# inicialización del array utilizando un  array de python


In [7]:
#Creación del array utilizando una función basada en rangos
# minimo, maximo, número de elementos del array


In [8]:
#Inicializar el array con valores aleatorios


In [9]:
# valores aleatorios


In [10]:
# Inicialización del array utilizando una función personalizada


## Acceso a los elementos de un array

### Array unidimensional

In [11]:
#Creación de un Array Unidemensional




In [12]:
#Accediendo al tercer elemento del array


In [13]:
#Accediendo al tercer y cuarto elemento del array


In [14]:
#Acceder a los elementos en saltos de dos iniciando en la posición 2


### Array multidimensional

In [15]:
#creación de un array multidimensional


In [16]:
#Accediendo al cuarto alemento del array


In [17]:
#Accediendo a la segunda fila


## Modificación de un Array

In [18]:
#Creación de un  array unidimensional inicializado con el rango de elementos 0-10


In [19]:
#cambiar la dimensiones del array y su longitudes


In [20]:
#devolviendo el array a una sola dimensión ravel()


## Operaciones aritméticas con Arrays

In [21]:
#creación de dos arrays unidimensionales



In [22]:
#suma


In [23]:
#resta
import numpy as np
a = np.array([1,2,3,4,5])
b = np.array([6,7,8,9,10])
print(a - b)

[-5 -5 -5 -5 -5]


In [24]:
#multiplicar
print(a * b)

[ 6 14 24 36 50]


## Broadcasting

Si se aplican operaciones aritméticas sobre Arrays que no tienen la misma forma (shape) Numpy aplica un propiedad que se denomina Broadcasting.

In [25]:
#creación de dos arrays unidimensionales
a = np.arange(5)
b = np.array([3])
print("shape array1", a.shape)
print("array1 ",a)
print("shape array2", b.shape)
print("array2 ",b)

shape array1 (5,)
array1  [0 1 2 3 4]
shape array2 (1,)
array2  [3]


In [26]:
#suma arreglos diferente tamaño
c=a+b
print("shape array resultado", c.shape)
print("array resultado ",c)

shape array resultado (5,)
array resultado  [3 4 5 6 7]


In [27]:
#creación de dos arrays multidimensional y unidimensional
a = np.arange(6)
print("array a", a)
a.shape=(2,3)
print("array a", a)
print("shape array1", a.shape)



array a [0 1 2 3 4 5]
array a [[0 1 2]
 [3 4 5]]
shape array1 (2, 3)


In [28]:
b = np.arange(6,18,4)
print("array b", b)
print("shape array2", b.shape)

array b [ 6 10 14]
shape array2 (3,)


In [29]:
c=a+b
print("shape array resultado", c.shape)
print("array resultado ",c)

shape array resultado (2, 3)
array resultado  [[ 6 11 16]
 [ 9 14 19]]


Ejemplo 1: suma de un escalar a un arreglo (se quiere sumar un solo número acada elemento del arreglo

In [30]:
#crear arreglo de ejemplo
a = np.array([1, 2, 3, 4])
print(a)
#sumar un escalar
b = a + 5
print(b)

[1 2 3 4]
[6 7 8 9]


Ejemplo 2: suma de un matriz que tiene 3x3 y quiere sumar un arreglo a una sola dimensión

In [31]:
#crear matriz 3x3
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(a)
#crear arreglo de ejemplo
b = np.array([1, 2, 3])

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [32]:
c=a+b
print(c)

[[ 2  4  6]
 [ 5  7  9]
 [ 8 10 12]]


Ejemplo 3 Multiplicación de un arreglo a una matriz(broadcasting en una dimensión extra)
queremos multiplicar cada elemento del arreglo por cada columna de la matriz

In [33]:
#crear matriz de 3x3
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(a)
#crear arreglo de ejemplo
b = np.array([1, 2, 3])
#multiplicación de la matriz y el arreglo
c=a*b[:,np.newaxis]
print(c)


[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ 1  2  3]
 [ 8 10 12]
 [21 24 27]]


Ejercicio para practica

1 Resta entre un arreglo y una matriz
crea un arreglo  de una dimensión con valores [10,20,30], crea una matriz de tamaño 3x3 con valores secuenciales, resta el arreglo a cada fila de la matriz usando broadcasting


In [34]:
# crear un matriz secuencial de 3x3
a = np.arange(1,10).reshape(3,3)
print(a)
b=([10,20,30])
print(b)
c=a-b
print(c)


[[1 2 3]
 [4 5 6]
 [7 8 9]]
[10, 20, 30]
[[ -9 -18 -27]
 [ -6 -15 -24]
 [ -3 -12 -21]]


2 operaciones con matrices de diferente formas:
crear una matriz  de 2x3 y otra de 3x1 utilizar broadcasting para sumar matriz a y matriz b

In [35]:
#crear matriz 2x3
a=np.arange(1,7).reshape(2,3)
print(a)
#crear matriz 3x1
b=np.arange(1,4).reshape(3,1)
print(b)


[[1 2 3]
 [4 5 6]]
[[1]
 [2]
 [3]]


In [36]:
c=a+b.T
print(c)

[[2 4 6]
 [5 7 9]]


3 División con broadcasting
crear una matriz de 4x2 con valores secuenciales. Divide la matriz en un arreglo de 1D[2,4]

In [37]:
#crear matriz de 4x2
a=np.arange(1,9).reshape(4,2)
print(a)
#crear arreglo de 1D
b=np.array([2,4])
print(b)
c=a/b
print(c)


[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[2 4]
[[0.5 0.5]
 [1.5 1. ]
 [2.5 1.5]
 [3.5 2. ]]


Contexto: análisis de datos meteorológicos

Imaginemos que estás analizando datos meteorológicos de temperaturas en diferentes ciudades durante una semana. Los datos de temperaturas están en Celsius, pero necesitas convertirlos a fahrenheit para un informe internacional.
Objetivo:

usaremos broadcasting para:

1.	convertir una matriz de temperaturas en Celsius a Fahrenheit

2.	comparar las temperaturas promedio de cada día con el promedio semanal y calcular la desviación


Datos

tenemos una matriz de temperaturas (en grados Celsius) para 5 ciudades durante 7 días




In [38]:
import numpy as np
# Matriz de temperatura en celsius(5 ciudades x 7 días)
temperatura_celsius=np.array([
    [25,27,26,22,24,25,23], #ciudad 1
    [30,32,31,29,28,30,29], #ciudad 2
    [20,21,19,22,20,21,23], #ciudad 3
    [15,14,16,15,14,15,15], #ciudad 4
    [10,12,11,13,12,10,11], #ciudad 5
])
print("temperatura celsius")
print(temperatura_celsius)





temperatura celsius
[[25 27 26 22 24 25 23]
 [30 32 31 29 28 30 29]
 [20 21 19 22 20 21 23]
 [15 14 16 15 14 15 15]
 [10 12 11 13 12 10 11]]


Paso1: Comvertir celsius a fahrenheit usando Broadcasting
Fórmula  fahrenheit= celsius x 1.8+32

In [39]:
#convertir a fahrenheit usando broadcasting
temperatura_fahrenheit=temperatura_celsius*1.8+32
print("temperatura fahrenheit")
print(temperatura_fahrenheit)

temperatura fahrenheit
[[77.  80.6 78.8 71.6 75.2 77.  73.4]
 [86.  89.6 87.8 84.2 82.4 86.  84.2]
 [68.  69.8 66.2 71.6 68.  69.8 73.4]
 [59.  57.2 60.8 59.  57.2 59.  59. ]
 [50.  53.6 51.8 55.4 53.6 50.  51.8]]


Paso 2 Calcular el promedio semanal por ciudad
para obtener una idea general de la temperatura media en cada ciudad durante la semana, calculamos el promedio de cada fila

In [40]:
#promedio semanal de temperatura en cada ciudad
promedio_semanal=temperatura_fahrenheit.mean(axis=1)
print("promedio semanal")
print(promedio_semanal)
#promedio días de temperatura
promedio_diario=temperatura_fahrenheit.mean(axis=0)
print("promedio diario")
print(promedio_diario)
#promedio de todas las temperaturas
promedio_total=temperatura_fahrenheit.mean()
print("promedio total")
print(promedio_total)
#Desviación diaria por ciudad en comparación con el promedio diario
desviacion_diaria=temperatura_fahrenheit-promedio_diario
print("desviación diaria")
print(desviacion_diaria)

promedio semanal
[76.22857143 85.74285714 69.54285714 58.74285714 52.31428571]
promedio diario
[68.   70.16 69.08 68.36 67.28 68.36 68.36]
promedio total
68.51428571428573
desviación diaria
[[  9.    10.44   9.72   3.24   7.92   8.64   5.04]
 [ 18.    19.44  18.72  15.84  15.12  17.64  15.84]
 [  0.    -0.36  -2.88   3.24   0.72   1.44   5.04]
 [ -9.   -12.96  -8.28  -9.36 -10.08  -9.36  -9.36]
 [-18.   -16.56 -17.28 -12.96 -13.68 -18.36 -16.56]]


## Funciones estadísticas sobre Arrays

In [41]:
#creación de array unidimensional
a = np.arange(1,20,2)
print(a)
#media de los elementos del array
print(np.mean(a))

[ 1  3  5  7  9 11 13 15 17 19]
10.0


Funciones universales eficientes proporcionadas por numpy: **ufunc**

In [42]:
#suma de elementos del array
print(np.sum(a))

100


In [43]:
#suma de elementos del array
print(a.sum())

100


In [44]:
#cuadrado de los elementos de un array
print(np.square(a))

[  1   9  25  49  81 121 169 225 289 361]


In [45]:
#raiz cuadarda de los elementos del array
print(np.sqrt(a))

[1.         1.73205081 2.23606798 2.64575131 3.         3.31662479
 3.60555128 3.87298335 4.12310563 4.35889894]
